name: flutter_md_viewer
description: .md 파일로 Web Page 자동 생성하기

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.10+3
  flutter_highlighter: ^0.1.1
  google_fonts: ^3.0.1
  very_good_analysis: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.5

flutter:

  uses-material-design: true

  assets:
    - assets/

