name: flutter_md_viewer
description: .md 파일로 Web Page 자동 생성하기

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.0
  flutter_highlighter: ^0.1.1
  google_fonts: ^3.0.1
  very_good_analysis: ^3.0.1

  provider: ^6.0.3
  logger: ^1.1.0
  lottie: ^1.4.2

  # animated text kit
  animated_text_kit: ^4.2.2

  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - pages/
    - pages/test/
    - page_index.md
    - assets/
    - assets/animations/
    - assets/animations/images/
