name: flutter_md_viewer
description: Markdown만 작성해도 웹페이지가 생성되는 웹은 가능한가?

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.10+3
  flutter_highlighter: ^0.1.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

