name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd ./build/web
          pwd
          git init
          git config --global user.email kms0644804@naver.com
          git config --global user.name boring-km
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/boring-km/flutter_md_viewer.git 
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f